### ISSUE TITLE
Outdated mods showing in green

### ISSUE THREAD

**Issue by Simon04090** [NotEnoughMods/NEM-VersionChecker#2]
I have a very strange issue. Mods that are outdated are showing green on the mod list even though they are already updated on the list for the webpage. It's for example happening for Optifine and Computercraft, both of them have a strange versioning format. We already discussed it on IRC yesterday evening (GMT). I think it's an issue with Utils.isNewer returning a "wrong" result because it thinks 1.65 is a "higher" version number than 1.7.

**Comment by Simon04090** [comment]
I have a working "fix" for the problem. I just changed it to check if the current version is different from the remote version and if it is I'm predicting it's an outdated version. I could prepare a PR if you want.

**Comment by Lunatrius** [comment]
Instead of doing that, adding an orange color for mods with different versions seems like a better idea.

**Comment by Pyker** [comment]
To be honest, 1.65 is indeed newer than 1.7, by versioning logic. It seems the ComputerCraft team messed up the versioning.

**Comment by Simon04090** [comment]
I could do that but I won't be at my computer till mid next week.

**Comment by bochen415** [comment]
My investigation revealed:
Fastcraft 1.19 installed (current), green, NEM showing 1.17.
Cause: the mcmod.info file in the jar is invalid, has wrong version (1.17 should be 1.19)

PneumaticCraft 1.5.3-51 (outdated) installed, green, NEM showing 1.5.3-err.
Cause: the mcmod.info file in the jar is invalid, has wrong version (1.5.3-err should be 1.5.3-51)

Jabba outdated installed, yellow (not detected).
Cause:bad modid in NEM (jabba should be JABBA)
Fixed minutes ago.

**Comment by Pyker** [comment]
Closing this because 1) ComputerCraft messed up their versioning, 2) Optifine isn't a Forge mod and therefore has no mod id, 3) This issue has been inactive for a while now.

Please reopen if this is still an issue.
